version: "3.0"

services:
  bento-box:
    image: bentorobotics/rosbox:robot
    container_name: bento-box-ros
    user: root
    restart: always
    privileged: true
    ipc: host
    pid: host
    mem_limit: 300mb
    environment:
        - EDU_ROBOT_NAMESPACE=bento
    network_mode: "host"
    volumes:
      - './launch-content:/launch-content'
      - '/dev:/dev'
    devices:
      - '/dev:/dev'
    command: bash -c 'cd /launch-content; ros2 launch bento-box.launch.py'
