/**:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "camera"
      pixel_format: "mjpeg2rgb"  # see usb_cam/supported_formats for list of supported formats
      image_width: 320
      image_height: 240
      camera_name: "Monocle"
      #camera_info_url: "package://usb_cam/config/camera_info.yaml"
      brightness: 32
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: true
      #white_balance: 4000
      autoexposure: true
      #exposure: 50
      autofocus: false
      focus: -1
