/**:
  ros__parameters:
# General Parameters
    tf_base_frame: base_link
    tf_footprint_frame: base_footprint
    use_sim_time: false

# Collision Avoidance
    collision_avoidance:
      enable: false
      distance_reduce_velocity: 0.6
      distance_velocity_zero: 0.05

# IMU Sensor
    imu:
      enable: false
      fusion_weight: 0.029999999329447746
      raw_data_mode: false

# Motor Controller
    motor_d:
      inverted: true
      closed_loop: true
      control_frequency: 16000
      encoder_inverted: true
      encoder_ratio: 64.0
      gear_ratio: 70.0
      max_rpm: 150.0
      pid/kd: 0.0
      pid/ki: 120.0
      pid/kp: 0.5
      weight_low_pass_encoder: 0.3
      weight_low_pass_set_point: 0.2



# Range Sensor
    range:
      front:
        left:
          field_of_view: 0.1745329201221466
          range_max: 5.0
          range_min: 0.009999999776482582

        right:
          field_of_view: 0.1745329201221466
          range_max: 5.0
          range_min: 0.009999999776482582

      rear:
        left:
          field_of_view: 0.1745329201221466
          range_max: 5.0
          range_min: 0.009999999776482582

        right:
          field_of_view: 0.1745329201221466
          range_max: 5.0
          range_min: 0.009999999776482582

# Drive Kinematic
    skid:
      length:
        x: 0.25
        y: 0.3199999928474426
      wheel_diameter: 0.17000000178813934

    mecanum:
      length:
        x: 0.25
        y: 0.36000001430511475
      wheel_diameter: 0.10000000149011612
